//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagmentSystem1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedRoom
    {
        public int ResID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Nights { get; set; }
        public string BookDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
    }
}
