<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DBClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="Lecture14.Properties.Settings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Doctor" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="DId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Specialization" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Designation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Doctor_Appointment" Member="Appointments" ThisKey="DId" OtherKey="DId" Type="Appointment" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Doctor_Appointment" Member="Doctor" ThisKey="DId" OtherKey="DId" Type="Doctor" IsForeignKey="true" />
      <Association Name="Patient_Appointment" Member="Patient" ThisKey="PId" OtherKey="PId" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="PId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Patient_Appointment" Member="Appointments" ThisKey="PId" OtherKey="PId" Type="Appointment" />
    </Type>
  </Table>
</Database>