//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseOffering
    {
        public CourseOffering()
        {
            this.GradeReports = new HashSet<GradeReport>();
        }
    
        public int OfferingId { get; set; }
        public Nullable<int> CourseNumber { get; set; }
        public Nullable<int> Semester { get; set; }
        public string Year { get; set; }
        public string Instructor { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<GradeReport> GradeReports { get; set; }
    }
}
