//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseOfferings = new HashSet<CourseOffering>();
            this.PreReqs = new HashSet<PreReq>();
            this.PreReqs1 = new HashSet<PreReq>();
        }
    
        public int CourseNumber { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CreditHours { get; set; }
        public string Department { get; set; }
    
        public virtual ICollection<CourseOffering> CourseOfferings { get; set; }
        public virtual ICollection<PreReq> PreReqs { get; set; }
        public virtual ICollection<PreReq> PreReqs1 { get; set; }
    }
}
